buildVariable: true
familyName: Noto Sans New Tai Lue
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 9676
    start: 9676
recipeProvider: noto
sources:
- NotoSansNewTaiLue.glyphs
